_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  asset_injector: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  csv_serialization: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  migrate: 0
  migrate_alerts: 0
  migrate_audience: 0
  migrate_audience2016: 0
  migrate_booklist_cats: 0
  migrate_databases: 0
  migrate_db_access: 0
  migrate_db_cats: 0
  migrate_db_subjects: 0
  migrate_db_types: 0
  migrate_event_tags: 0
  migrate_events: 0
  migrate_file: 0
  migrate_fullscreens: 0
  migrate_heroes: 0
  migrate_home_page: 0
  migrate_items: 0
  migrate_library_info: 0
  migrate_locations: 0
  migrate_meeting_rooms: 0
  migrate_plus: 0
  migrate_priorities: 0
  migrate_remote_locations: 0
  migrate_rooms: 0
  migrate_rotators: 0
  migrate_sponsors: 0
  migrate_zones: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  rdf: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  structure_sync: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  user: 0
  views_autocomplete_filters: 0
  views_conditional: 0
  views_data_export: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  webform: 0
  webform_views: 0
  pathauto: 1
  views: 10
  standard: 1000
theme:
  olivero: 0
  claro: 0
  uswds_base: 0
  apl: 0
profile: standard
